reads: # Specify the order and methods for each read processing step. If no method is specified, the step will not be performed.
  subsampling: "seqtk" # OPT - specify method of subsampling. Allowed: "seqtk", "null".
  deduplication: null
  trimming: null
  decontamination: null
  _generate_fastqc_for: ["subsampling"] # OPT - specify which steps to generate fastqc for. Allowed: "original"."subsampling", "trimming", "decontamination", "deduplication" or empty list (default: empty list).

### HYPERPARAMETERS #############################

reads__subsampling__seqtk:
  seed: 1
  n_reads: 300
  reduce_memory: false

### RESOURCES #############################

max_threads: 2
max_mem_mb: 6192

resources:
  reads__fastqc_mem_mb: 2048

threads:
  reads__fastqc: 1
