flow:
  - "decontaminated"

fastqc_reports:
  - "original"
  - "decontaminated"

### HYPERPARAMETERS #############################

decontamination:
  kraken_dir: "path_to_kraken/k2_viral_20230314" # Directory containing kraken DB files. If does not exist, will be downloaded using the dirname.
  # get KRAKEN_TAG from https://benlangmead.github.io/aws-indexes/k2
  exclude_taxa_ids: # list of taxonomy IDs to exclude.
    - 9606 # Homo Sapiens
  exclude_children: false # Whether to exclude reads classified at more specific levels than specified taxonomy ID levels.
  exclude_ancestors: false # Whether to exclude reads classified at all taxonomy levels between root and the specified taxonomy ID levels.
  save_memory: true # If true, kraken limits RAM memory usage but sacrifices speed.

### RESOURCES #############################

max_threads: 2
max_mem_mb: 6192

resources:
  fastqc_mem_mb: 2048

threads:
  fastqc: 1
  decontamination: 8
