reads__processing_flow:
  - "trimmed"

fastqc_reports:
  - "original"
  - "trimmed"

### HYPERPARAMETERS #############################

reads__trimming:
  shorten_to_length: 500 # OPT shorten to this length.
  max_n_bases: 3 # OPT Discard reads with more than the specified number of bases. The fifth step.
  max_expected_errors: 3 # OPT - discard reads with more expected errors than this.
  min_length_r1: 35 # OPT, minimum R1 read length. The fourth step.
  min_length_r2: 35 # OPT, minimum R2 read length. The fourth step.
  quality_cutoff_from_5_end_r1: 20 # OPT cutoff on 5' end of R1 read. The second step.
  quality_cutoff_from_3_end_r1: 20 # OPT cutoff on 3' end of R1 read. The second step.
  quality_cutoff_from_5_end_r2: 20 # OPT cutoff on 5' end of R2 read. The second step.
  quality_cutoff_from_3_end_r2: 20 # OPT cutoff on 3' end of R2 read. The second step.
  adapter_removal:
    do: false

### RESOURCES #############################

max_threads: 2
max_mem_mb: 6192

resources:
  reads__trimming_mem_mb: 4096
  fastqc_mem_mb: 2048

threads:
  reads__trimming: 4
  fastqc: 1
