"$schema": https://json-schema.org/draft/2020-12/schema
"$ref": "#/definitions/Reads"
definitions:
  Reads:
    type: object
    additionalProperties: true
    properties:
      pepfile:
        type: string
        description: "Path to the PEP file containing the info how to load the data."
        default: "config/pep/config.yaml"
      reads:
        type: object
        description: "Specify the order and methods for each read processing step. If no method is specified, the step will not be performed."
        "$ref": "#/definitions/ReadsProcessing"
      max_threads:
        type: integer
        description: "Number of maximum threads to use in jobs."
        default: 8
        Minimum: 1
      max_mem_mb:
        type: integer
        description: "Maximum memory in megabytes to allocate for any job."
        Minimum: 2048
        default: 4096
      resources:
        type: object
        "$ref": "#/definitions/Resources"
      threads:
        type: object
        "$ref": "#/definitions/Threads"
    required:
      - max_threads
      - max_mem_mb
      - reads
    allOf:
      - if:
          properties:
            reads:
              properties:
                decontamination:
                  type: string
                  const: "kraken"
        then:
          properties:
            reads__decontamination__kraken:
              type: object
              "$ref": "#/definitions/ReadsDecontaminationKraken"
              description: "Relevant only if reads->decontamination is set to kraken."
          required:
            - reads__decontamination__kraken
          message: "reads__decontamination__kraken is required if reads->decontamination is set to kraken."
      - if:
          properties:
            reads:
              properties:
                trimming:
                  type: string
                  const: "cutadapt"
        then:
          properties:
            reads__trimming__cutadapt:
              type: object
              "$ref": "#/definitions/ReadsTrimmingCutadapt"
              description: "Relevant only if reads->trimming is set to cutadapt."
          required:
            - reads__trimming__cutadapt
          message: "reads__trimming__cutadapt is required if reads->trimming is set to cutadapt."
      - if:
          properties:
            reads:
              properties:
                subsampling:
                  type: string
                  const: "seqtk"
        then:
          properties:
            reads__subsampling__seqtk:
              type: object
              "$ref": "#/definitions/ReadsSubsamplingSeqtk"
              description: "Relevant only if reads->subsampling is set to seqtk."
          required:
            - reads__subsampling__seqtk
          message: "reads__subsampling__seqtk is required if reads->subsampling is set to seqtk."
      - if:
          properties:
            reads:
              properties:
                deduplication:
                  type: string
                  const: "fastuniq"
        then:
          properties:
            reads__deduplication__fastuniq:
              type: object
              "$ref": "#/definitions/ReadsDeduplicationFastuniq"
              description: "Relevant only if reads->deduplication is set to fastuniq. There are no parameters to be defined."
          required:
            - reads__deduplication__fastuniq
          message: "reads__deduplication__fastuniq is required if reads->deduplication is set to fastuniq."

      # request resources based on specified tasks
      - if:
          properties:
            reads:
              properties:
                _generate_fastqc_for:
                  minItems: 1
        then:
          properties:
            threads:
              required:
                - reads__fastqc
            resources:
              required:
                - reads__fastqc_mem_mb
      - if:
          properties:
            reads:
              properties:
                trimming:
                  type: string
        then:
          properties:
            threads:
              required:
                - reads__trimming
            resources:
              required:
                - reads__trimming_mem_mb
      - if:
          properties:
            reads:
              properties:
                decontamination:
                  type: string
        then:
          properties:
            threads:
              required:
                - reads__decontamination
      - if:
          properties:
            reads:
              properties:
                deduplication:
                  type: string
        then:
          properties:
            threads:
              required:
                - reads__deduplication
    title: Reads
  ReadsSubsamplingSeqtk:
    type: object
    additionalProperties: false
    properties:
      seed:
        type: integer
        default: 1
        description: "Seed value to use for random number generator."
      n_reads:
        type: integer
        description: "Number of reads to subsample."
        minimum: 1
      reduce_memory:
        type: boolean
        default: True
        description: "Set to 2-pass mode, slower but with less memory used."
    required:
      - seed
      - n_reads
      - reduce_memory
    title: ReadsSubsampling
  ReadsDeduplicationFastuniq:
    type: object
    additionalProperties: false
    description: "There are no parameters to be defined for Fastuniq deduplication."
    default: {}
  ReadsDecontaminationKraken:
    type: object
    additionalProperties: false
    properties:
      kraken_dir:
        type: string
        description: "Directory with the kraken DB files. If does not exist, the workflow tries to download DB by using the basename. See https://benlangmead.github.io/aws-indexes/k2."
        pattern: '.*k2_.*_\d{8}\/?$'
        examples: ["/data/genome/metagenome/kraken/k2_pluspf_20240112"]
      exclude_taxa_ids:
        type: array
        description: "List of taxonomy IDs for excluding logic. Example: 9606 - Homo Sapiens of rank=species."
        minItems: 1
        items:
          type: integer
        default: [9606]
      exclude_children:
        type: boolean
        default: false
        description: "Whether to exclude reads classified at more specific levels than specified taxonomy ID levels."
      exclude_ancestors:
        type: boolean
        default: false
        description: "Whether to exclude reads classified at all taxonomy levels between root and the specified taxonomy ID levels."
      save_memory:
        type: boolean
        description: "If true, kraken limits RAM memory usage but sacrifices speed."
        default: true
      generate_krona:
        type: boolean
        description: "If true, krona is generated from kraken report."
        default: false
      krona_dir:
        type: [string, "null"]
        description: "Directory where krona dataset is located, or where will be downloaded."
        examples: ["/data/genome/taxonomy/krona/2023-12-03/"]
    required:
      - exclude_taxa_ids
      - kraken_dir
      - exclude_children
      - exclude_ancestors
      - save_memory
      - generate_krona
      - krona_dir
    title: ReadsDecontamination
    if:
      properties:
        generate_krona:
          const: true
    then:
      properties:
        krona_dir:
          type: string
          pattern: '.*/\d{4}-\d{2}-\d{2}\/?$'
      message: "reads__decontamination__kraken->krona_dir must be valid if generate_krona is True."
  ReadsTrimmingCutadapt:
    type: object
    additionalProperties: false
    properties:
      cut_from_start_r1:
        type: [integer, "null"]
        description: "Removes a specified number of bases from the beginning of the R1 read."
        minimum: 0
        default: null
      cut_from_start_r2:
        type: [integer, "null"]
        description: "Removes a specified number of bases from the beginning of the R2 read."
        minimum: 0
        default: null
      cut_from_end_r1:
        type: [integer, "null"]
        description: "Removes a specified number of bases from the end of the R1 read."
        minimum: 0
        default: null
      cut_from_end_r2:
        type: [integer, "null"]
        default: null
        description: "Removes a specified number of bases from the end of the R2 read."
        minimum: 0
      quality_cutoff_from_3_end_r1:
        type: integer
        description: "Removes lower quality bases from the 3' end of the R1 read."
        default: 20
        minimum: 0
      quality_cutoff_from_5_end_r1:
        type: integer
        description: "Removes lower quality bases from the 5' end of the R1 read."
        default: 20
        minimum: 0
      quality_cutoff_from_3_end_r2:
        type: integer
        description: "Removes lower quality bases from the 3' end of the R2 read."
        default: 20
        minimum: 0
      quality_cutoff_from_5_end_r2:
        type: integer
        description: "Removes lower quality bases from the 5' end of the R2 read."
        default: 20
        minimum: 0
      nextseq_trimming_mode:
        type: boolean
        default: false
        description: "Modify quality-trimming algorithm to expect two-color chemistry data (NextSeq)."
      do_adapter_removal:
        type: boolean
        default: false
        description: "Whether to do adapter removal or not."
      adapter_removal:
        type: object
        "$ref": "#/definitions/AdapterRemoval"
        description: "Relevant only if do_adapter_removal is set to true."
      shorten_to_length:
        type: [integer, "null"]
        description: "Shorten each read to the specified length. Corresponds to the cutadapt length parameter."
        minimum: 0
        default: null
      trim_N_bases_on_ends:
        type: boolean
        default: false
        description: "Set to true to trim 'N' bases on ends."
      min_length_r1:
        type: [integer, "null"]
        description: "Discards R1 reads shorter than this. Recommended to set at least to 1, to discard empty reads."
        minimum: 0
        default: null
        examples: [45]
      min_length_r2:
        type: [integer, "null"]
        description: "Discards R2 reads shorter than this. Recommended to set at least to 1, to discard empty reads."
        minimum: 0
        default: null
        examples: [45]
      max_length_r1:
        type: [integer, "null"]
        description: "Discards R1 reads longer than this value."
        minimum: 0
        default: null
      max_length_r2:
        type: [integer, "null"]
        description: "Discards R2 reads longer than this value."
        minimum: 0
        default: null
      max_n_bases:
        type: [integer, "null"]
        description: "Removes reads with more 'N' bases than the specified number."
        minimum: 0
        default: null
      max_expected_errors:
        type: [integer, "null"]
        description: "Discard reads whose expected number of errors exceeds this value."
        minimum: 0
        default: null
    required:
      - quality_cutoff_from_3_end_r1
      - quality_cutoff_from_5_end_r1
      - quality_cutoff_from_3_end_r2
      - quality_cutoff_from_5_end_r2
      - nextseq_trimming_mode
      - do_adapter_removal
      - cut_from_start_r1
      - cut_from_start_r2
      - cut_from_end_r1
      - cut_from_end_r2
      - shorten_to_length
      - trim_N_bases_on_ends
      - min_length_r1
      - min_length_r2
      - max_length_r1
      - max_length_r2
      - max_n_bases
      - max_expected_errors
    title: ReadsTrimmingCutadapt
    if:
      properties:
        do_adapter_removal:
          const: true
    then:
      required:
        - adapter_removal
  AdapterRemoval:
    type: object
    additionalProperties: false
    properties:
      action:
        type: string
        enum:
          - "retain"
          - "trim"
          - "mask"
          - "none"
          - "lowercase"
        default: "trim"
        description: "Defines an action to perform with the found adapter."
      overlap:
        type: integer
        default: 3
        description: "Minimum number of bases required to overlap with the adapter."
      error_rate:
        type: number
        default: 0.1
        exclusiveMinimum: 0
        description: "Error tolerance used when searching for adapter."
      times:
        type: integer
        default: 1
        description: "How many times to repeat adapter removal."
      keep_trimmed_only:
        type: boolean
        default: false
        description: "Discard reads with no adapters found."
      adapters_anywhere_file:
        type: [string, "null"]
        description: "Fasta file path with adapters to be matched 'anywhere'."
      adapters_3_end_file:
        type: [string, "null"]
        description: "Fasta file path with adapters to be matched at 3'end."
      adapters_5_end_file:
        type: [string, "null"]
        description: "Fasta file path with adapters to be matched at 5'end."
    required:
      - overlap
      - error_rate
      - times
      - action
      - adapters_anywhere_file
      - adapters_3_end_file
      - adapters_5_end_file
    title: AdapterRemoval
  ReadsProcessing:
    type: object
    additionalProperties: true
    properties:
      subsampling:
        type: [string, "null"]
        description: "Subsampling method, if not set, subsampling will not be performed."
        enum:
          - "seqtk"
          - null
        default: null
      trimming:
        type: [string, "null"]
        description: "Trimming method, if not set, trimming will not be performed."
        enum:
          - "cutadapt"
          - null
        default: null
        examples: ["cutadapt"]
      decontamination:
        type: [string, "null"]
        description: "Decontamination method, if not set, decontamination will not be performed."
        enum:
          - "kraken"
          - null
        default: null
        examples: ["kraken"]
      deduplication:
        type: [string, "null"]
        description: "Deduplication method, if not set, deduplication will not be performed."
        enum:
          - "fastuniq"
          - null
        default: null
      _generate_fastqc_for:
        type: array
        description: "Specify which steps to generate fastqc for."
        items:
          type: string
          enum:
            - "original"
            - "subsampling"
            - "trimming"
            - "decontamination"
            - "deduplication"
        default: null
        examples: [["original", "decontamination"]]
    allOf:
      - if:
          properties:
            _generate_fastqc_for:
              contains:
                const: "deduplication"
        then:
          properties:
            deduplication:
              type: string
              description: "Reads->Deduplication is required if fastqc is requested for deduplication."
      - if:
          properties:
            _generate_fastqc_for:
              contains:
                const: "trimming"
        then:
          properties:
            trimming:
              type: string
              description: "Reads-trimming is required if fastqc is requested for trimming."
      - if:
          properties:
            _generate_fastqc_for:
              contains:
                const: "subsampling"
        then:
          properties:
            subsampling:
              type: string
              description: "Reads->subsampling is required if fastqc is requested for subsampling."
      - if:
          properties:
            _generate_fastqc_for:
              contains:
                const: "decontamination"
        then:
          properties:
            decontamination:
              type: string
              description: "Reads->decontamination is required if fastqc is requested for decontamination."
    title: ReadsProcessing
    required:
      - _generate_fastqc_for
  Resources:
    type: object
    additionalProperties: true
    properties:
      reads__trimming_mem_mb:
        type: integer
        description: "Memory in MB to reserve for trimming."
        default: 4096
      reads__fastqc_mem_mb:
        type: integer
        description: "Memory in MB to reserve for fastqc."
        default: 2048
    title: Resources
  Threads:
    type: object
    additionalProperties: true
    properties:
      reads__trimming:
        type: integer
        description: "Number of threads to use for trimming."
        default: 4
      reads__deduplication:
        type: integer
        description: "Number of threads to use for deduplication."
        default: 4
      reads__decontamination:
        type: integer
        description: "Number of threads to use for decontamination."
        default: 8
      reads__fastqc:
        type: integer
        description: "Number of threads to use for fastqc."
        default: 1
    title: Threads
