"$schema": https://json-schema.org/draft/2020-12/schema
"$ref": "#/definitions/Reads"
definitions:
  Reads:
    type: object
    additionalProperties: true
    properties:
      pepfile:
        type: string
        description: "Path to the PEP file containing the info how to load the data."
        default: "config/pep/config.yaml"
      reads:
        type: object
        "$ref": "#/definitions/ReadsProcessing"
      max_threads:
        type: integer
        description: "Number of maximum threads to use in jobs."
        default: 1
        Minimum: 1
      max_mem_mb:
        type: integer
        description: "Maximum memory in megabytes to allocate for any job."
        Minimum: 2048
        default: 2048
      reads__trimming__cutadapt:
        type: object
        "$ref": "#/definitions/ReadsTrimmingCutadapt"
      reads__subsampling__seqtk:
        type: object
        "$ref": "#/definitions/ReadsSubsamplingSeqtk"
      reads__decontamination__kraken:
        type: object
        "$ref": "#/definitions/ReadsDecontaminationKraken"
      resources:
        type: object
        "$ref": "#/definitions/Resources"
      threads:
        type: object
        "$ref": "#/definitions/Threads"
    required:
      - max_threads
      - max_mem_mb
      - reads
    allOf:
      - if:
          properties:
            reads:
              properties:
                decontamination:
                  type: string
                  const: "kraken"
        then:
          required:
            - reads__decontamination__kraken
          message: "reads__decontamination__kraken is required if reads->decontamination is set to kraken"
      - if:
          properties:
            reads:
              properties:
                trimming:
                  type: string
                  const: "cutadapt"
        then:
          required:
            - reads__trimming__cutadapt
          message: "reads__trimming__cutadapt is required if reads->trimming is set to cutadapt"
      - if:
          properties:
            reads:
              properties:
                subsampling:
                  type: string
                  const: "seqtk"
        then:
          required:
            - reads__subsampling__seqtk
          message: "reads__subsampling__seqtk is required if reads->subsampling is set to seqtk"

      # request resources based on specified tasks
      - if:
          properties:
            reads:
              properties:
                _generate_fastqc_for:
                  min_items: 1
        then:
          properties:
            threads:
              required:
                - reads__fastqc
            resources:
              required:
                - reads__fastqc_mem_mb
      - if:
          properties:
            reads:
              properties:
                trimming:
                  type: string
        then:
          properties:
            threads:
              required:
                - reads__trimming
            resources:
              required:
                - reads__trimming_mem_mb
      - if:
          properties:
            reads:
              properties:
                decontamination:
                  type: string
        then:
          properties:
            threads:
              required:
                - reads__decontamination
      - if:
          properties:
            reads:
              properties:
                deduplication:
                  type: string
        then:
          properties:
            threads:
              required:
                - reads__deduplication
    title: Reads
  ReadsSubsamplingSeqtk:
    type: object
    additionalProperties: false
    properties:
      seed:
        type: integer
        default: 1
      n_reads:
        type: integer
      reduce_memory:
        type: boolean
        default: True
    required:
      - seed
      - n_reads
      - reduce_memory
    title: ReadsSubsampling
  ReadsDecontaminationKraken:
    type: object
    additionalProperties: false
    properties:
      kraken_dir:
        type: string
        description: "Directory with the kraken DB files. If does not exist, the workflow tries to download DB by using the basename."
        pattern: '.*k2_.*_\d{8}$'
      exclude_taxa_ids:
        type: array
        description: "list of taxonomy IDs to exclude."
        min_items: 1
        items:
          type: integer
      exclude_children:
        type: boolean
        default: false
        description: "whether to exclude reads classified at more specific levels than specified taxonomy ID levels."
      exclude_ancestors:
        type: boolean
        default: false
        description: "whether to exclude reads classified at all taxonomy levels between root and the specified taxonomy ID levels."
      save_memory:
        type: boolean
        description: "if true, kraken limits RAM memory usage but sacrifices speed."
        default: true
    required:
      - exclude_taxa_ids
      - kraken_dir
      - exclude_children
      - exclude_ancestors
      - save_memory
    title: ReadsDecontamination
  ReadsTrimmingCutadapt:
    type: object
    additionalProperties: false
    properties:
      adapter_removal:
        type: object
        "$ref": "#/definitions/AdapterRemoval"
        default: {}
      shorten_to_length:
        type: [integer, "null"]
        description: "Optional. Shorten each read to the specified length. Corresponds to the cutadapt length parameter."
        minimum: 0
      cut_from_start_r2:
        type: [integer, "null"]
        description: "Optional. Removes a specified number of bases from the beginning of the read."
        minimum: 0
      cut_from_end_r1:
        type: [integer, "null"]
        description: "Optional. Removes a specified number of bases from the end of the read."
        minimum: 0
      cut_from_start_r1:
        type: [integer, "null"]
        description: "Optional. Removes a specified number of bases from the beginning of the read."
        minimum: 0
      cut_from_end_r2:
        type: [integer, "null"]
        description: "Optional. Removes a specified number of bases from the end of the read."
        minimum: 0
      max_n_bases:
        type: [integer, "null"]
        description: "Optional. Removes reads with more N bases than the specified number."
        minimum: 0
      max_expected_errors:
        type: [integer, "null"]
        description: "Optional. Discard reads whose expected number of errors exceeds this value."
        minimum: 0
      max_length_r1:
        type: [integer, "null"]
        description: "Optional. Discards R1 reads longer than this."
        minimum: 0
      trim_N_bases_on_ends:
        type: [boolean, "null"]
        description: "Optional. Set to true to trim N bases on ends."
      max_length_r2:
        type: [integer, "null"]
        description: "Optional. Discards R2 reads longer than this."
        minimum: 0
      min_length_r1:
        type: [integer, "null"]
        description: "Optional. Discards R1 reads shorter than this. Recommended to set at least to 1, to discard empty reads."
        minimum: 0
      min_length_r2:
        type: [integer, "null"]
        description: "Optional. Discards R2 reads shorter than this. Recommended to set at least to 1, to discard empty reads."
        minimum: 0
      quality_cutoff_from_3_end_r1:
        type: [integer, "null"]
        description: "Optional. Removes lower quality bases from the 3' end of the R1 read."
        minimum: 0
      quality_cutoff_from_5_end_r1:
        type: [integer, "null"]
        description: "Optional. Removes lower quality bases from the 5' end of the R1 read."
        minimum: 0
      quality_cutoff_from_3_end_r2:
        type: [integer, "null"]
        description: "Optional. Removes lower quality bases from the 3' end of the R2 read."
        minimum: 0
      quality_cutoff_from_5_end_r2:
        type: [integer, "null"]
        description: "Optional. Removes lower quality bases from the 5' end of the R2 read."
        minimum: 0
    required:
      - adapter_removal
    title: ReadsTrimming
  AdapterRemoval:
    type: object
    additionalProperties: false
    properties:
      do:
        type: boolean
        default: false
        description: "Whether to do adapter removal or not."
      adapters_fasta:
        type: string
        description: "Adapters fasta used for adapter trimming."
      overlap:
        type: integer
        default: 3
        description: "Minimum number of bases required to overlap with the adapter."
      error_rate:
        type: number
        default: 0.1
        exclusiveMinimum: 0
        description: "Error tolerance used when searching for adapter."
      times:
        type: integer
        default: 1
        description: "How many times to repeat adapter removal."
      action:
        type: string
        enum:
          - "retain"
          - "trim"
          - "mask"
          - "none"
          - "lowercase"
        default: "trim"
        description: "Defines an action to perform with the found adapter."
      keep_trimmed_only:
        type: boolean
        default: false
        description: "Discard reads with no adapters found."
      read_location:
        type: string
        enum:
          - "anywhere"
          - "regular"
          - "front"
        default: "anywhere"
        description: "Path to the adapter file. Search for adapters anywhere in the read."
    required:
      - do
    if:
      properties:
        do:
          const: true
    then:
      required:
        - adapters_fasta
        - overlap
        - error_rate
        - times
        - action
        - keep_trimmed_only
        - read_location
    title: AdapterRemoval
  ReadsProcessing:
    type: object
    additionalProperties: true
    properties:
      subsampling:
        type: [string, "null"]
        description: "Specification of subsampling method."
        enum:
          - "seqtk"
          - null
      trimming:
        type: [string, "null"]
        description: "Specification of trimming method."
        enum:
          - "cutadapt"
          - null
      decontamination:
        type: [string, "null"]
        description: "Specification of decontamination method."
        enum:
          - "kraken"
          - null
      deduplication:
        type: [string, "null"]
        description: "Specification of deduplication method."
        enum:
          - "fastuniq"
          - null
      _generate_fastqc_for:
        type: array
        default: []
        items:
          type: string
          enum:
            - "decontamination"
            - "trimming"
            - "subsampling"
            - "deduplication"
            - "original"
    allOf:
      - if:
          properties:
            _generate_fastqc_for:
              contains:
                const: "deduplication"
        then:
          properties:
            deduplication:
              type: string
              description: "Reads->Deduplication is required if fastqc is requested for deduplication"
      - if:
          properties:
            _generate_fastqc_for:
              contains:
                const: "trimming"
        then:
          properties:
            trimming:
              type: string
              description: "Reads-trimming is required if fastqc is requested for trimming"
      - if:
          properties:
            _generate_fastqc_for:
              contains:
                const: "subsampling"
        then:
          properties:
            subsampling:
              type: string
              description: "Reads->subsampling is required if fastqc is requested for subsampling"
      - if:
          properties:
            _generate_fastqc_for:
              contains:
                const: "decontamination"
        then:
          properties:
            decontamination:
              type: string
              description: "Reads->decontamination is required if fastqc is requested for decontamination"
    title: ReadsProcessing
    required:
      - _generate_fastqc_for
  Resources:
    type: object
    additionalProperties: true
    properties:
      reads__trimming_mem_mb:
        type: integer
        description: "Memory in MB to reserve for trimming."
        default: 2048
      reads__fastqc_mem_mb:
        type: integer
        description: "Memory in MB to reserve for fastqc."
        default: 2048
    title: Resources
    required:
      - reads__trimming_mem_mb
  Threads:
    type: object
    additionalProperties: true
    properties:
      reads__trimming:
        type: integer
        description: "Number of threads to use for trimming."
        default: 1
      reads__deduplication:
        type: integer
        description: "Number of threads to use for deduplication."
        default: 1
      reads__decontamination:
        type: integer
        description: "Number of threads to use for decontamination."
        default: 1
      reads__fastqc:
        type: integer
        description: "Number of threads to use for fastqc."
        default: 1
    title: Threads
